### ISSUE TITLE
Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

### ISSUE THREAD

**Issue by luutruong** [fifsky/ssh-action#23]
YML setup:

```yml

name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Executing remote command
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          args: "-tt -vvv"
          command: "cd ${{ secrets.DEPLOY_PATH }} && bash scripts/ci-deploy.sh"
```
