### ISSUE TITLE
Workflow is successful even if fails on remote server

### ISSUE THREAD

**Issue by sokoloowski** [fifsky/ssh-action#26]
Can I detect if command on my VPS failed and show it in Github (red cross)? For now, with basic example, workflow shows as successful, even if command is not found.

Code:
```yml
name: build
on:
  push:
    branches:
    - stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect via SSH
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/my-app
            git pull
            npm install
            npm run test
            pm2 reload app
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
```

`npm install` fails on my server, then `npm run test` is failing too (command not found), but I get green check at the end:
![image](https://user-images.githubusercontent.com/39133910/130624674-da9540e5-f190-45d2-87ad-186a59ecf3f1.png)
