### ISSUE TITLE
Using environment variables to the command script

### ISSUE THREAD

**Issue by ilyamochalov** [fifsky/ssh-action#3]
Hello there,

I really appreciate the work you put into this action, I am using it now.
There would be great if we were able to pass environmental variables to the `command`, for example:
```
    - name: ssh remote
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ${{ ENV_VAR }}
          ls -a
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        key: ${{ secrets.KEY}}
```
where `ENV_VAR` is an environmental variable created on previous step/actions. Do you know any work arounds for this?

**Comment by fifsky** [comment]
Hi @ilyamochalov   

> Each step runs in its own process in the virtual environment and has access to the workspace and filesystem. Because steps run in their own process, changes to environment variables are not preserved between steps.

You must defined workflow env, The following documentation will be helpful

https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/#env-at-the-workflow-and-job-level

https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#env

**Comment by aaronbushnell** [comment]
I'm having this issue as well when my environment variables are defined at the workflow level. Here's my `.yml` file:

```yml
name: My Action

on: pull_request

env:
  APPNAME: app_name

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2-beta

      - name: Install
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd apps/${{APPNAME}}
          host: ${{secrets.SSH_HOSTNAME}}
          user: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          args: "-tt"
```

And the error I get from GitHub is:
```
- Your workflow file was invalid: The pipeline is not valid. .github/workflows/main.yml (Line: 21, Col: 24): Unrecognized named-value: 'APPNAME'. Located at position 1 within expression: APPNAME
```

**Comment by aaronbushnell** [comment]
Ah, I see what needs to happen here. `${{APPNAME}}` should be `${{env.APPNAME}}`. Here's an example of the final `.yml` file:

```yml
name: My Action

on: pull_request

env:
  APPNAME: app_name

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2-beta

      - name: Install
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd apps/${{env.APPNAME}}
          host: ${{secrets.SSH_HOSTNAME}}
          user: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          args: "-tt"
```
