### ISSUE TITLE
sammy@65.123.123.133: Permission denied (publickey).

### ISSUE THREAD

**Issue by simanacci** [fifsky/ssh-action#35]
**Workflow**
```yaml
- name: Deploy
  uses: fifsky/ssh-action@master
  with:
    host: ${{ vars.DROPLET_IP }}
    key: ${{ secrets.SSH_KEY }}
    port: 22
    user: sammy
    command: |
        cd ~
        export FOO=${{ secrets.FOO }} BAR=${{ secrets.BAR }}
        docker-compose down
        docker-compose pull
        docker-compose up -d
    args: "-tt -vvv"
```
**File Permissions**
```terminal
sammy@ubuntu-s-1vcpu-2gb-blr1-01:~/.ssh$ stat -c "%a %n" *
600 authorized_keys
```
```terminal
sammy@ubuntu-s-1vcpu-2gb-blr1-01:~$ stat -c "%a %n" .ssh
700 .ssh
```
**sshd_config**
`cat /etc/ssh/sshd_config`
https://gist.github.com/simanacci/134c838a474fdc25433dcd91c359509e
```terminal
sammy@ubuntu-s-1vcpu-2gb-blr1-01:/etc/ssh/sshd_config.d$ ls
50-cloud-init.conf  60-cloudimg-settings.conf

sammy@ubuntu-s-1vcpu-2gb-blr1-01:/etc/ssh/sshd_config.d$ sudo cat 50-cloud-init.conf
PasswordAuthentication no

sammy@ubuntu-s-1vcpu-2gb-blr1-01:/etc/ssh/sshd_config.d$ sudo cat 60-cloudimg-settings.conf
PasswordAuthentication no
```
**Error**
```terminal
debug1: No more authentication methods to try.
sammy@65.123.123.133: Permission denied (publickey).
```
https://gist.github.com/simanacci/4ce05a4a03d0b34a3db22423aec2a24c

Root is disabled. `sammy` is a `sudoer`. I can connect to the Droplet successfully via `ssh sammy@ip_address` without a Passphrase.
