### ISSUE TITLE
Step fails without any error

### ISSUE THREAD

**Issue by blbrdv** [fifsky/ssh-action#36]
My action config:

```
name: Release

on:
  push:
    tags:
    - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      
       ...

      - name: Release
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /***
            git pull
            docker compose pull
            docker compose up -d
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          pass: ${{ secrets.SERVER_PASSPHRASE }}

```

Step logs:

```
Run fifsky/ssh-action@master
  with:
    command: cd /***
  git pull
  docker compose pull
  docker compose up -d
  
    host: ***
    key: ***
    pass: ***
    port: 22
  env:
    image_version: 0.8.2
    
/usr/bin/docker run --name d7f37e482395d4eea48a7afc37fa7cee42f3a_b0c402 --label 5d7f37 
--workdir /github/workspace --rm -e "image_version" -e "INPUT_COMMAND" -e "INPUT_HOST" 
-e "INPUT_USER" -e "INPUT_KEY" -e "INPUT_PASS" -e "INPUT_PORT" -e "INPUT_KEYFILE" 
-e "INPUT_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" 
-e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" 
-e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" 
-e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" 
-e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" 
-e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" 
-e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" 
-e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" 
-e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" 
-e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GIT

 Warning: This action does not currently support host verification; verification is disabled.
 
cd /***
git pull
docker compose pull
docker compose up -d
exit $?
Start Run Command
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface] [-b bind_address]
           [-c cipher_spec] [-D [bind_address:]port] [-E log_file]
           [-e escape_char] [-F configfile] [-I pkcs11] [-i identity_file]
           [-J destination] [-L address] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-P tag] [-p port] [-R address]
           [-S ctl_path] [-W host:port] [-w local_tun[:remote_tun]]
           destination [command [argument ...]]
       ssh [-Q query_option]
```

Looks like ssh command used incorrectly 🤷🏻‍♂️ or i miss something

**Comment by blbrdv** [comment]
After some attempts i found out solution:
1. Set `PasswordAuthentication no` in `/etc/ssh/sshd_config` on the server and restarted ssh `systemctl restart ssh`
2. Regenerate sha key without password (not recommended) and put it in github variables
3. Change action config to:
```
      - name: Release
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_PRIVATE_KEY}}
          command: |
            ***
```

Now everything worked as i wanted.
