### ISSUE TITLE
Passwords must be escaped if contains & and probably other characters

### ISSUE THREAD

**Issue by AbdullahGheith** [fifsky/ssh-action#37]
If you do something like this:

```
        with:
          host: ${{ secrets.DROPLET_IP }}
          user: ${{ secrets.DROPLET_USERNAME }}
          pass: ${{ secrets.DROPLET_PASSWORD }}
```

And your password is Hello&ToYou,
you must enter the password in DROPLET_PASSWORD as: Hello\\&ToYou
