### ISSUE TITLE
Error: Operation timed out

### ISSUE THREAD

**Issue by proartti** [fifsky/ssh-action#4]
I am trying to use the action to run a .sh file to sync and build a Laravel/React app.

The action successfully connects via ssh and runs the file but there is no output and after 30sec it exits with timeout error. 

I start running a couple of tests I got the same error just copying and paste your example code.

I am trying to connect to a Ubuntu 18 server.
Any tips?

Action out put:

```
Warning: This action does not currently support host verification; verification is disabled. 
 
/home/***/deploy/deploy_dev.sh
Start Run Command
Pseudo-terminal will not be allocated because stdin is not a terminal.
ssh: connect to host *** port 22: Operation timed out
##[error]Docker run failed with exit code 255
```

**Comment by fifsky** [comment]
Hi,There may be two possibilities
1、Blocked by firewall
2、Try ssh -t -t(or ssh -tt for short) to force pseudo-tty allocation even if stdin isn't a terminal.
https://stackoverflow.com/questions/7114990/pseudo-terminal-will-not-be-allocated-because-stdin-is-not-a-terminal

For the second problem, I added a `args` parameter to pass the extra parameters of SSH

See https://github.com/fifsky/ssh-action#options

```
- name: ls -a via ssh
  uses: fifsky/ssh-action@master
  with:
    command: |
      cd /tmp
      ls -a
    host: ${{ secrets.HOST }}
    user: root
    key: ${{ secrets.PRIVATE_KEY}}
    args:"-tt"
```
